pipeline {
    agent any
    environment {
        env = "production"
    }

    stages {
        stage ('Git clone deployment') {
            steps('git clone'){
                git branch: 'main', url: 'https://github.com/Seyi-Ojo/ThirdSemExam.git'
            }
        }
        
        stage ('Deploy page') {
            steps {
                dir('KuberProj') {
                    sshagent(['ubuntu']){
                        sh "scp -o strictHostKeyChecking=no deployment.yaml ubuntu@54.159.56.93:/home/ubuntu"
                    }
                    script {
                        try{
                            sh "ssh ubuntu@54.159.56.93 kubectl create -f deployment.yaml"
                        } catch(error){
                            sh "ssh ubuntu@54.159.56.93 kubectl apply -f deployment.yaml"
                        }
                    }
                }
            }
        }
        
        stage('git clone') {
            steps {
                git branch: 'master', url: 'https://github.com/Seyi-Ojo/microservices-demo.git'
            }
        }
        stage('Deploy socks application') {
            steps {
                dir('deploy/kubernetes') {
                    sshagent(['ubuntu']){
                        sh "scp -o strictHostKeyChecking=no complete-demo.yaml ubuntu@54.159.56.93:/home/ubuntu"
                    }
                    script {
                        try{
                            sh "ssh ubuntu@54.159.56.93 kubectl apply -f complete-demo.yaml"
                        } catch(error){
                            sh "ssh ubuntu@54.159.56.93 kubectl create -f complete-demo.yaml"
                        }
                    }
                }
            }
        }
    }
}
